"""Generate performance reports"""

from typing import Dict, Any

def generate_markdown_report(validation_result: Dict[str, Any]) -> str:
    """Generate markdown performance report"""

    result = validation_result

    report = f"""# Performance Validation Report

**Platform:** {result['platform']}
**Status:** {'✅ PASS' if result['passed'] else '❌ FAIL'}

## Targets vs Measured

| Metric | Target | Measured | Status |
|--------|--------|----------|--------|
| FPS | {result['target']['fps']} | {result['measured']['avg_fps']:.1f} | {'✅' if result['measured']['avg_fps'] >= result['target']['fps'] * 0.9 else '❌'} |
| Frame Time | {result['target']['frame_time_ms']:.2f}ms | {result['measured']['avg_frame_time_ms']:.2f}ms | {'✅' if result['measured']['avg_frame_time_ms'] <= result['target']['frame_time_ms'] * 1.1 else '❌'} |
| Draw Calls | {result['target']['draw_calls']} | {result['measured']['avg_draw_calls']} | {'✅' if result['measured']['avg_draw_calls'] <= result['target']['draw_calls'] else '❌'} |
| Memory | N/A | {result['measured']['memory_mb']}MB | ℹ️ |

## Issues Found

"""

    if not result['issues']:
        report += "*No issues found - performance meets all targets!*\n"
    else:
        for issue in result['issues']:
            severity_emoji = {'high': '🔴', 'medium': '🟡', 'low': '🟢'}
            report += f"""
### {severity_emoji[issue['severity']]} {issue['category']} ({issue['severity'].upper()})

**Problem:** {issue['message']}

**Suggestion:** {issue['suggestion']}

"""

    report += f"""
## Performance Breakdown

- **CPU Time:** {result['measured']['cpu_time_ms']:.2f}ms
- **GPU Time:** {result['measured']['gpu_time_ms']:.2f}ms
- **Total Memory:** {result['measured']['memory_mb']}MB

---
*Generated by Game Dev Supercharger Performance Validator*
"""

    return report
